/*==============================================================*/
/* Nom de SGBD :  SQLite                                        */
/* Date de cr�ation :  10/04/2025 16:04:05                      */
/*==============================================================*/

-- Drop existing tables if they exist
DROP TABLE IF EXISTS EXECUTE;
DROP TABLE IF EXISTS RESULTAT;
DROP TABLE IF EXISTS PLUGIN;
DROP TABLE IF EXISTS UTILISATEUR;

-- Create UTILISATEUR table
CREATE TABLE UTILISATEUR (
    ID_UTILISATEUR INTEGER PRIMARY KEY,
    PRENOM_UTILISATEUR VARCHAR(100),
    ROLE_UTILISATEUR VARCHAR(50),
    EMAIL_UTILISATEUR VARCHAR(100),
    DERNIERE_CONNEXION DATETIME
);

-- Create PLUGIN table
CREATE TABLE PLUGIN (
    ID_PLUGIN INTEGER PRIMARY KEY,
    NOM_PLUGIN VARCHAR(100),
    DATE_CREATION DATETIME,
    DESCRIPTION TEXT,
    VERSION VARCHAR(20),
    NTLM_KEY VARCHAR(255)
);

-- Create EXECUTE table
CREATE TABLE EXECUTE (
    ID_UTILISATEUR INTEGER,
    ID_PLUGIN INTEGER,
    DATE_EXECUTION DATETIME,
    PRIMARY KEY (ID_UTILISATEUR, ID_PLUGIN),
    FOREIGN KEY (ID_UTILISATEUR) REFERENCES UTILISATEUR(ID_UTILISATEUR),
    FOREIGN KEY (ID_PLUGIN) REFERENCES PLUGIN(ID_PLUGIN)
);

-- Create RESULTAT table
CREATE TABLE RESULTAT (
    ID_RESULTAT INTEGER PRIMARY KEY,
    ID_PLUGIN INTEGER,
    DATE_RESULTAT DATETIME,
    STATUT VARCHAR(50),
    DETAILS TEXT,
    FOREIGN KEY (ID_PLUGIN) REFERENCES PLUGIN(ID_PLUGIN)
);

